vich_uploader:
    db_driver: orm

#mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        mouvement_images:
            uri_prefix: /images/mouvementListe
            upload_destination: '%kernel.project_dir%/public/images/mouvementListe'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        typeMouvement_images:
            uri_prefix: /images/type
            upload_destination: '%kernel.project_dir%/public/images/type'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
